name: Trigger Docker Compose Repo

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docker-compose-repo Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ORG_TOKEN }} 
          repository: developeerz/docker-compose
          event-type: trigger-from-app2
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
